# permissions for end users to view higresscontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: higresscontroller-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: higressoperator
    app.kubernetes.io/part-of: higressoperator
    app.kubernetes.io/managed-by: kustomize
  name: higresscontroller-viewer-role
rules:
- apiGroups:
  - operator.higress.io
  resources:
  - higresscontrollers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.higress.io
  resources:
  - higresscontrollers/status
  verbs:
  - get
