# permissions for end users to edit higressgateways.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: higressgateway-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: higressoperator
    app.kubernetes.io/part-of: higressoperator
    app.kubernetes.io/managed-by: kustomize
  name: higressgateway-editor-role
rules:
- apiGroups:
  - operator.higress.io
  resources:
  - higressgateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.higress.io
  resources:
  - higressgateways/status
  verbs:
  - get
